# Generated by Django 4.1 on 2022-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("traits", "0001_initial"),
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="traits",
            field=models.ManyToManyField(to="traits.trait"),
        ),
    ]
